# Generated by Django 2.2.5 on 2019-10-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProjectList',
            fields=[
                ('technicalsolutions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productsapp.TechnicalSolutions')),
            ],
            bases=('productsapp.technicalsolutions',),
        ),
    ]
